#!/bin/sh
clear

echo "Enter root password if your not logged into root the the now so you dont get constant (Enter root password...)"

sudo su

ls -l

if [ -f /etc/gdm3/daemon.conf ]
  then
    echo "\n\nSaving our file to system's original /etc/gdm3/daemon.conf* files...\n"
    cp -f -b -p -v /($here)/daemon.conf /etc/gdm3/daemon.conf
    echo "\n...Done.\n"
fi
